### PR TITLE
Add new quote

### PR DESCRIPTION
**Pull request by robahl**

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
@robahl **The source of truth is missing in PR description.**
Can you please add the relevant link to the quote?

**Comment by robahl** [comment]
@vinitshahdeo It's my own source of inspiration. I think people need to see it.

**Comment by vinitshahdeo** [comment]
@robahl That's great:) 👍 💯

**Comment by robahl** [comment]
> @robahl That's great:) 👍 💯

Nice! Let's merge this to spread my good advice :)

**Comment by robahl** [comment]
@vinitshahdeo When is this gonna be merged mate :)

**Pull request closed without merging**
