### PR TITLE
Add Nikola Tesla Code.

### PR DESCRIPTION
**Pull request by nayyyhaa**

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
@nayyyhaa Thanks for the PR. I'll review and merge it soon.
> **You may look into a few **[good first issues](https://vinitshahdeo.github.io/HacktoberFest2K19/)** which are **[up for grabs](https://github.com/vinitshahdeo/HacktoberFest2K19).****

### :white_check_mark: [Link to the repository](https://github.com/vinitshahdeo/HacktoberFest2K19)

**Comment by nayyyhaa** [comment]
Added Nikola Tesla quote.
source: https://www.learning-mind.com/nikola-tesla-quotes/

Refers to #4

**Comment by nayyyhaa** [comment]
Kindly check and please merge. :)

**Comment by vinitshahdeo** [comment]
@nayyyhaa Sure, will merge it soon!

**Pull request closed without merging**
